### ISSUE TITLE
Epic - Locations Admin

### ISSUE THREAD

**Issue by havok25103** [havok25103/character-sheet#42]
**Possible Features / Things to Explore:**

- [x] CRUD on location data
- [x] WISIWIG style articles
- [x] Active content editor styling
- [x] Scope global styling that conflicts with editor to classes
- [x] Map image uploads
- [x] Sigil image uploads
- [x] Data Backups
