### ISSUE TITLE
Add Dungeons Admin

### ISSUE THREAD

**Issue by havok25103** [havok25103/character-sheet#60]
**Possible Features / Things to Explore:**

Borrow Heavily from Locations

- [ ] CRUD on location data
- [ ] WISIWIG style articles
- [ ] Active content editor styling
- [ ] Scope global styling that conflicts with editor to classes
- [ ] Map image uploads
- [ ] Interactive map pins
- [ ] Character, Creature, Faction, or NPC associations with map pins
- [ ] Data Backups
